
package org.ttinana.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IPlService", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IPlService {


    /**
     * 
     * @param privredniSubjektiUlazniPodaci
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.ArrayOfPrivredniSubjekat
     */
    @WebMethod(operationName = "PreuzmiPodatkeOPrivrednomSubjektu", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/PreuzmiPodatkeOPrivrednomSubjektu")
    @WebResult(name = "PrivredniSubjektiPodaci", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "PreuzmiPodatkeOPrivrednomSubjektu", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.PreuzmiPodatkeOPrivrednomSubjektu")
    @ResponseWrapper(localName = "PreuzmiPodatkeOPrivrednomSubjektuResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.PreuzmiPodatkeOPrivrednomSubjektuResponse")
    public ArrayOfPrivredniSubjekat preuzmiPodatkeOPrivrednomSubjektu(
        @WebParam(name = "privredniSubjektiUlazniPodaci", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
        PrivredniSubjektiUlazniPodaci privredniSubjektiUlazniPodaci);

    /**
     * 
     * @param privredniSubjektiPromenePoDatumuUlazniPodaci
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.ArrayOfPrivredniSubjekat
     */
    @WebMethod(operationName = "PreuzmiPromenePodatakaOPrivrednimSubjektima", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/PreuzmiPromenePodatakaOPrivrednimSubjektima")
    @WebResult(name = "privredniSubjektiPodaci", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "PreuzmiPromenePodatakaOPrivrednimSubjektima", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.PreuzmiPromenePodatakaOPrivrednimSubjektima")
    @ResponseWrapper(localName = "PreuzmiPromenePodatakaOPrivrednimSubjektimaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.PreuzmiPromenePodatakaOPrivrednimSubjektimaResponse")
    public ArrayOfPrivredniSubjekat preuzmiPromenePodatakaOPrivrednimSubjektima(
        @WebParam(name = "privredniSubjektiPromenePoDatumuUlazniPodaci", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
        PrivredniSubjektiPromenePoDatumu privredniSubjektiPromenePoDatumuUlazniPodaci);

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciODelatnostima", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciODelatnostima")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciODelatnostima", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciODelatnostima")
    @ResponseWrapper(localName = "SviPodaciODelatnostimaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciODelatnostimaResponse")
    public Sifarnik sviPodaciODelatnostima();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciODrzavama", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciODrzavama")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciODrzavama", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciODrzavama")
    @ResponseWrapper(localName = "SviPodaciODrzavamaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciODrzavamaResponse")
    public Sifarnik sviPodaciODrzavama();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOFunkcijamaOsnivacaZaduzbineIliFondacije", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOFunkcijamaOsnivacaZaduzbineIliFondacije")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOFunkcijamaOsnivacaZaduzbineIliFondacije", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOFunkcijamaOsnivacaZaduzbineIliFondacije")
    @ResponseWrapper(localName = "SviPodaciOFunkcijamaOsnivacaZaduzbineIliFondacijeResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOFunkcijamaOsnivacaZaduzbineIliFondacijeResponse")
    public Sifarnik sviPodaciOFunkcijamaOsnivacaZaduzbineIliFondacije();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOFunkcijamaZakonskogZastupnikaPrivrednogDrustva", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOFunkcijamaZakonskogZastupnikaPrivrednogDrustva")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOFunkcijamaZakonskogZastupnikaPrivrednogDrustva", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOFunkcijamaZakonskogZastupnikaPrivrednogDrustva")
    @ResponseWrapper(localName = "SviPodaciOFunkcijamaZakonskogZastupnikaPrivrednogDrustvaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOFunkcijamaZakonskogZastupnikaPrivrednogDrustvaResponse")
    public Sifarnik sviPodaciOFunkcijamaZakonskogZastupnikaPrivrednogDrustva();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOGrupamaDelatnosti", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOGrupamaDelatnosti")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOGrupamaDelatnosti", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOGrupamaDelatnosti")
    @ResponseWrapper(localName = "SviPodaciOGrupamaDelatnostiResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOGrupamaDelatnostiResponse")
    public Sifarnik sviPodaciOGrupamaDelatnosti();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOMestima", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOMestima")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOMestima", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOMestima")
    @ResponseWrapper(localName = "SviPodaciOMestimaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOMestimaResponse")
    public Sifarnik sviPodaciOMestima();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOOblastimaDelatnosti", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOOblastimaDelatnosti")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOOblastimaDelatnosti", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOOblastimaDelatnosti")
    @ResponseWrapper(localName = "SviPodaciOOblastimaDelatnostiResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOOblastimaDelatnostiResponse")
    public Sifarnik sviPodaciOOblastimaDelatnosti();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOOblicimaOrganizovanjaZaduzbineIliFondacije", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOOblicimaOrganizovanjaZaduzbineIliFondacije")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOOblicimaOrganizovanjaZaduzbineIliFondacije", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOOblicimaOrganizovanjaZaduzbineIliFondacije")
    @ResponseWrapper(localName = "SviPodaciOOblicimaOrganizovanjaZaduzbineIliFondacijeResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOOblicimaOrganizovanjaZaduzbineIliFondacijeResponse")
    public Sifarnik sviPodaciOOblicimaOrganizovanjaZaduzbineIliFondacije();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOOdsecimaDelatnosti", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOOdsecimaDelatnosti")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOOdsecimaDelatnosti", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOOdsecimaDelatnosti")
    @ResponseWrapper(localName = "SviPodaciOOdsecimaDelatnostiResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOOdsecimaDelatnostiResponse")
    public Sifarnik sviPodaciOOdsecimaDelatnosti();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOOkruzima", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOOkruzima")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOOkruzima", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOOkruzima")
    @ResponseWrapper(localName = "SviPodaciOOkruzimaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOOkruzimaResponse")
    public Sifarnik sviPodaciOOkruzima();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOOpstinama", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOOpstinama")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOOpstinama", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOOpstinama")
    @ResponseWrapper(localName = "SviPodaciOOpstinamaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOOpstinamaResponse")
    public Sifarnik sviPodaciOOpstinama();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOPravnimFormama", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOPravnimFormama")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOPravnimFormama", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOPravnimFormama")
    @ResponseWrapper(localName = "SviPodaciOPravnimFormamaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOPravnimFormamaResponse")
    public Sifarnik sviPodaciOPravnimFormama();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOSektorimaDelatnosti", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOSektorimaDelatnosti")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOSektorimaDelatnosti", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOSektorimaDelatnosti")
    @ResponseWrapper(localName = "SviPodaciOSektorimaDelatnostiResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOSektorimaDelatnostiResponse")
    public Sifarnik sviPodaciOSektorimaDelatnosti();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOStatusimaPreduzetnika", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOStatusimaPreduzetnika")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOStatusimaPreduzetnika", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOStatusimaPreduzetnika")
    @ResponseWrapper(localName = "SviPodaciOStatusimaPreduzetnikaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOStatusimaPreduzetnikaResponse")
    public Sifarnik sviPodaciOStatusimaPreduzetnika();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOStatusimaPrivrednogDrustva", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOStatusimaPrivrednogDrustva")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOStatusimaPrivrednogDrustva", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOStatusimaPrivrednogDrustva")
    @ResponseWrapper(localName = "SviPodaciOStatusimaPrivrednogDrustvaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOStatusimaPrivrednogDrustvaResponse")
    public Sifarnik sviPodaciOStatusimaPrivrednogDrustva();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOStatusimaUdruzenja", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOStatusimaUdruzenja")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOStatusimaUdruzenja", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOStatusimaUdruzenja")
    @ResponseWrapper(localName = "SviPodaciOStatusimaUdruzenjaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOStatusimaUdruzenjaResponse")
    public Sifarnik sviPodaciOStatusimaUdruzenja();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOStatusimaZaduzbineIliFondacije", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOStatusimaZaduzbineIliFondacije")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOStatusimaZaduzbineIliFondacije", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOStatusimaZaduzbineIliFondacije")
    @ResponseWrapper(localName = "SviPodaciOStatusimaZaduzbineIliFondacijeResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOStatusimaZaduzbineIliFondacijeResponse")
    public Sifarnik sviPodaciOStatusimaZaduzbineIliFondacije();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipoviimaOblastiOstvarivanjaCiljevaUdruzenja", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipoviimaOblastiOstvarivanjaCiljevaUdruzenja")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipoviimaOblastiOstvarivanjaCiljevaUdruzenja", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipoviimaOblastiOstvarivanjaCiljevaUdruzenja")
    @ResponseWrapper(localName = "SviPodaciOTipoviimaOblastiOstvarivanjaCiljevaUdruzenjaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipoviimaOblastiOstvarivanjaCiljevaUdruzenjaResponse")
    public Sifarnik sviPodaciOTipoviimaOblastiOstvarivanjaCiljevaUdruzenja();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipoviimaZabeleskiUdruzenja", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipoviimaZabeleskiUdruzenja")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipoviimaZabeleskiUdruzenja", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipoviimaZabeleskiUdruzenja")
    @ResponseWrapper(localName = "SviPodaciOTipoviimaZabeleskiUdruzenjaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipoviimaZabeleskiUdruzenjaResponse")
    public Sifarnik sviPodaciOTipoviimaZabeleskiUdruzenja();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipovimaCiljevaZaduzbineIliFondacije", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipovimaCiljevaZaduzbineIliFondacije")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipovimaCiljevaZaduzbineIliFondacije", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipovimaCiljevaZaduzbineIliFondacije")
    @ResponseWrapper(localName = "SviPodaciOTipovimaCiljevaZaduzbineIliFondacijeResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipovimaCiljevaZaduzbineIliFondacijeResponse")
    public Sifarnik sviPodaciOTipovimaCiljevaZaduzbineIliFondacije();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipovimaClanaPrivrednogDrustva", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipovimaClanaPrivrednogDrustva")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipovimaClanaPrivrednogDrustva", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipovimaClanaPrivrednogDrustva")
    @ResponseWrapper(localName = "SviPodaciOTipovimaClanaPrivrednogDrustvaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipovimaClanaPrivrednogDrustvaResponse")
    public Sifarnik sviPodaciOTipovimaClanaPrivrednogDrustva();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipovimaFunkcijeZastupnikaZaduzbineIliFondacije", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipovimaFunkcijeZastupnikaZaduzbineIliFondacije")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipovimaFunkcijeZastupnikaZaduzbineIliFondacije", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipovimaFunkcijeZastupnikaZaduzbineIliFondacije")
    @ResponseWrapper(localName = "SviPodaciOTipovimaFunkcijeZastupnikaZaduzbineIliFondacijeResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipovimaFunkcijeZastupnikaZaduzbineIliFondacijeResponse")
    public Sifarnik sviPodaciOTipovimaFunkcijeZastupnikaZaduzbineIliFondacije();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipovimaJezika", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipovimaJezika")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipovimaJezika", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipovimaJezika")
    @ResponseWrapper(localName = "SviPodaciOTipovimaJezikaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipovimaJezikaResponse")
    public Sifarnik sviPodaciOTipovimaJezika();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipovimaKapitalaPrivrednogDrustva", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipovimaKapitalaPrivrednogDrustva")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipovimaKapitalaPrivrednogDrustva", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipovimaKapitalaPrivrednogDrustva")
    @ResponseWrapper(localName = "SviPodaciOTipovimaKapitalaPrivrednogDrustvaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipovimaKapitalaPrivrednogDrustvaResponse")
    public Sifarnik sviPodaciOTipovimaKapitalaPrivrednogDrustva();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipovimaKapitalaZaduzbineIliFondacije", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipovimaKapitalaZaduzbineIliFondacije")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipovimaKapitalaZaduzbineIliFondacije", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipovimaKapitalaZaduzbineIliFondacije")
    @ResponseWrapper(localName = "SviPodaciOTipovimaKapitalaZaduzbineIliFondacijeResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipovimaKapitalaZaduzbineIliFondacijeResponse")
    public Sifarnik sviPodaciOTipovimaKapitalaZaduzbineIliFondacije();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipovimaLica", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipovimaLica")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipovimaLica", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipovimaLica")
    @ResponseWrapper(localName = "SviPodaciOTipovimaLicaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipovimaLicaResponse")
    public Sifarnik sviPodaciOTipovimaLica();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipovimaNacinaPromene", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipovimaNacinaPromene")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipovimaNacinaPromene", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipovimaNacinaPromene")
    @ResponseWrapper(localName = "SviPodaciOTipovimaNacinaPromeneResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipovimaNacinaPromeneResponse")
    public Sifarnik sviPodaciOTipovimaNacinaPromene();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipovimaNazivaUdruzenja", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipovimaNazivaUdruzenja")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipovimaNazivaUdruzenja", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipovimaNazivaUdruzenja")
    @ResponseWrapper(localName = "SviPodaciOTipovimaNazivaUdruzenjaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipovimaNazivaUdruzenjaResponse")
    public Sifarnik sviPodaciOTipovimaNazivaUdruzenja();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipovimaPoslovnogSubjekta", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipovimaPoslovnogSubjekta")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipovimaPoslovnogSubjekta", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipovimaPoslovnogSubjekta")
    @ResponseWrapper(localName = "SviPodaciOTipovimaPoslovnogSubjektaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipovimaPoslovnogSubjektaResponse")
    public Sifarnik sviPodaciOTipovimaPoslovnogSubjekta();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipovimaRegistracionogPostupka", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipovimaRegistracionogPostupka")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipovimaRegistracionogPostupka", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipovimaRegistracionogPostupka")
    @ResponseWrapper(localName = "SviPodaciOTipovimaRegistracionogPostupkaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipovimaRegistracionogPostupkaResponse")
    public Sifarnik sviPodaciOTipovimaRegistracionogPostupka();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipovimaZabeleskiZaduzbineIliFondacije", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipovimaZabeleskiZaduzbineIliFondacije")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipovimaZabeleskiZaduzbineIliFondacije", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipovimaZabeleskiZaduzbineIliFondacije")
    @ResponseWrapper(localName = "SviPodaciOTipovimaZabeleskiZaduzbineIliFondacijeResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipovimaZabeleskiZaduzbineIliFondacijeResponse")
    public Sifarnik sviPodaciOTipovimaZabeleskiZaduzbineIliFondacije();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOVelicinamaPoslovnogSubjekta", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOVelicinamaPoslovnogSubjekta")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOVelicinamaPoslovnogSubjekta", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOVelicinamaPoslovnogSubjekta")
    @ResponseWrapper(localName = "SviPodaciOVelicinamaPoslovnogSubjektaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOVelicinamaPoslovnogSubjektaResponse")
    public Sifarnik sviPodaciOVelicinamaPoslovnogSubjekta();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOVrstamaZabelezbePreduzetnika", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOVrstamaZabelezbePreduzetnika")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOVrstamaZabelezbePreduzetnika", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOVrstamaZabelezbePreduzetnika")
    @ResponseWrapper(localName = "SviPodaciOVrstamaZabelezbePreduzetnikaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOVrstamaZabelezbePreduzetnikaResponse")
    public Sifarnik sviPodaciOVrstamaZabelezbePreduzetnika();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOVrstamaZabelezbePrivrednogDrustva", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOVrstamaZabelezbePrivrednogDrustva")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOVrstamaZabelezbePrivrednogDrustva", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOVrstamaZabelezbePrivrednogDrustva")
    @ResponseWrapper(localName = "SviPodaciOVrstamaZabelezbePrivrednogDrustvaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOVrstamaZabelezbePrivrednogDrustvaResponse")
    public Sifarnik sviPodaciOVrstamaZabelezbePrivrednogDrustva();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOVrstamaZabelezbeSportskogUdruzenja", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOVrstamaZabelezbeSportskogUdruzenja")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOVrstamaZabelezbeSportskogUdruzenja", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOVrstamaZabelezbeSportskogUdruzenja")
    @ResponseWrapper(localName = "SviPodaciOVrstamaZabelezbeSportskogUdruzenjaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOVrstamaZabelezbeSportskogUdruzenjaResponse")
    public Sifarnik sviPodaciOVrstamaZabelezbeSportskogUdruzenja();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOVrstamaOblikaOrganizovanjaSportskogUdruzenja", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOVrstamaOblikaOrganizovanjaSportskogUdruzenja")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOVrstamaOblikaOrganizovanjaSportskogUdruzenja", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOVrstamaOblikaOrganizovanjaSportskogUdruzenja")
    @ResponseWrapper(localName = "SviPodaciOVrstamaOblikaOrganizovanjaSportskogUdruzenjaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOVrstamaOblikaOrganizovanjaSportskogUdruzenjaResponse")
    public Sifarnik sviPodaciOVrstamaOblikaOrganizovanjaSportskogUdruzenja();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOVrstamaGraneSporta", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOVrstamaGraneSporta")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOVrstamaGraneSporta", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOVrstamaGraneSporta")
    @ResponseWrapper(localName = "SviPodaciOVrstamaGraneSportaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOVrstamaGraneSportaResponse")
    public Sifarnik sviPodaciOVrstamaGraneSporta();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOOblicimaOrganizovanjaUdruzenja", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOOblicimaOrganizovanjaUdruzenja")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOOblicimaOrganizovanjaUdruzenja", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOOblicimaOrganizovanjaUdruzenja")
    @ResponseWrapper(localName = "SviPodaciOOblicimaOrganizovanjaUdruzenjaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOOblicimaOrganizovanjaUdruzenjaResponse")
    public Sifarnik sviPodaciOOblicimaOrganizovanjaUdruzenja();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOStatusimaKomore", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOStatusimaKomore")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOStatusimaKomore", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOStatusimaKomore")
    @ResponseWrapper(localName = "SviPodaciOStatusimaKomoreResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOStatusimaKomoreResponse")
    public Sifarnik sviPodaciOStatusimaKomore();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipovimaNazivaKomore", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipovimaNazivaKomore")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipovimaNazivaKomore", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipovimaNazivaKomore")
    @ResponseWrapper(localName = "SviPodaciOTipovimaNazivaKomoreResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipovimaNazivaKomoreResponse")
    public Sifarnik sviPodaciOTipovimaNazivaKomore();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOStatusimaStecajneMase", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOStatusimaStecajneMase")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOStatusimaStecajneMase", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOStatusimaStecajneMase")
    @ResponseWrapper(localName = "SviPodaciOStatusimaStecajneMaseResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOStatusimaStecajneMaseResponse")
    public Sifarnik sviPodaciOStatusimaStecajneMase();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipovimaOsnivaca", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipovimaOsnivaca")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipovimaOsnivaca", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipovimaOsnivaca")
    @ResponseWrapper(localName = "SviPodaciOTipovimaOsnivacaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOTipovimaOsnivacaResponse")
    public Sifarnik sviPodaciOTipovimaOsnivaca();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOStatusimaSportskogUdruzenja", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOStatusimaSportskogUdruzenja")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOStatusimaSportskogUdruzenja", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOStatusimaSportskogUdruzenja")
    @ResponseWrapper(localName = "SviPodaciOStatusimaSportskogUdruzenjaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciOStatusimaSportskogUdruzenjaResponse")
    public Sifarnik sviPodaciOStatusimaSportskogUdruzenja();

    /**
     * 
     * @return
     *     returns businessentitydatamediationmodule.serviceexport.businessentitydatainterface.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciONacinuNastankaStecajneMase", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciONacinuNastankaStecajneMase")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciONacinuNastankaStecajneMase", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciONacinuNastankaStecajneMase")
    @ResponseWrapper(localName = "SviPodaciONacinuNastankaStecajneMaseResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "businessentitydatamediationmodule.serviceexport.businessentitydatainterface.SviPodaciONacinuNastankaStecajneMaseResponse")
    public Sifarnik sviPodaciONacinuNastankaStecajneMase();

}
