
package org.ttinana.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PlService", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", wsdlLocation = "https://service1.apr.gov.rs:4430/plwstest/PlService.svc?singleWsdl")
public class PlService
    extends Service
{

    private final static URL PLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PLSERVICE_EXCEPTION;
    private final static QName PLSERVICE_QNAME = new QName("http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", "PlService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://service1.apr.gov.rs:4430/plwstest/PlService.svc?singleWsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PLSERVICE_WSDL_LOCATION = url;
        PLSERVICE_EXCEPTION = e;
    }

    public PlService() {
        super(__getWsdlLocation(), PLSERVICE_QNAME);
    }

    public PlService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PLSERVICE_QNAME, features);
    }

    public PlService(URL wsdlLocation) {
        super(wsdlLocation, PLSERVICE_QNAME);
    }

    public PlService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PLSERVICE_QNAME, features);
    }

    public PlService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PlService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IPlService
     */
    @WebEndpoint(name = "CustomBinding_IPlService")
    public IPlService getCustomBindingIPlService() {
        return super.getPort(new QName("http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", "CustomBinding_IPlService"), IPlService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IPlService
     */
    @WebEndpoint(name = "CustomBinding_IPlService")
    public IPlService getCustomBindingIPlService(WebServiceFeature... features) {
        return super.getPort(new QName("http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", "CustomBinding_IPlService"), IPlService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PLSERVICE_EXCEPTION!= null) {
            throw PLSERVICE_EXCEPTION;
        }
        return PLSERVICE_WSDL_LOCATION;
    }

}
